version: "3.7"

services:

  traefik:
    image: traefik:2.2
    restart: always
    networks:
      - gateway
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.toml:/etc/traefik/traefik.toml
    ports:
      - 80:80
      - 443:443
      - 8080:8080

networks:
  gateway:
